* About
Validation data and runs for the RONEB method.
** Reference
If you use this repository or its parts please cite the corresponding publication or data source.
*** TODO Primary Publication
Submitted.
*** DONE Preprint
CLOSED: [2026-01-21 Wed 09:18]
A more accessible form of the same publication:
#+begin_quote
R. Goswami, M. Gunde, and H. Jónsson, “Reorienting off-path nudged elastic bands (RONEB) via minimum mode following,” Jan. 19, 2026, arXiv: arXiv:2601.12630. doi:10.48550/arXiv.2601.12630.
#+end_quote
*** HOLD Data source
:PROPERTIES:
:CUSTOM_ID: mca
:END:
At the Materials Cloud Archive.
#+begin_quote
Rohit Goswami, Miha Gunde, and Hannes Jónsson,   Reorienting off-path nudged elastic bands (RONEB) via minimum mode following, Materials Cloud Archive 2026.X (2026). doi:10.24435/materialscloud:fw-wq
#+end_quote
** Replication data
Remember to inflate the data using the ~materialscloud~ (section ref:mca) before using the output parsing scripts in the repository. Assuming that the ~.xz~ files have been downloaded to ~data~ relative to the repository root:
#+begin_src bash
export GITROOT=$(git rev-parse --show-toplevel)
cd $GITROOT
tar -xf nebviz_results.tar.xz && rm -rf nebviz_results.tar.xz
cp $GITROOT/nebviz_results.tar.xz $GITROOT/eonRuns
cd $GITROOT/eonRuns
tar -xf nebviz_results.tar.xz && rm -rf nebviz_results.tar.xz
#+end_src
* DONE Usage
CLOSED: [2025-12-08 Mon 03:39]
A reproducible setup for generating benchmarks discussed elsewhere [1 ([[https://github.com/TheochemUI/gpr_sella_repro][Github]]), 2 ([[https://github.com/HaoZeke/brms_idrot_repro/blob/main/readme.org][Github]]), 3 ([[https://github.com/theochemUI/otgpd_repro][Github]])].
** Setup and reproduction
See ~readme.org~ in ~eonRuns~.
** References
1. R. Goswami, M. Masterov, S. Kamath, A. Pena-Torres, and H. Jónsson, “Efficient Implementation of Gaussian Process Regression Accelerated Saddle Point Searches with Application to Molecular Reactions,” J. Chem. Theory Comput., July 2025, doi: 10.1021/acs.jctc.5c00866.
2. R. Goswami, “Bayesian hierarchical models for quantitative estimates for performance metrics applied to saddle search algorithms,” AIP Adv., vol. 15, no. 8, p. 85210, Aug. 2025, doi: 10.1063/5.0283639.
3. R. Goswami and H. Jónsson, “Adaptive Pruning for Increased Robustness and Reduced Computational Overhead in Gaussian Process Accelerated Saddle Point Searches,” ChemPhysChem, Nov. 2025, doi: 10.1002/cphc.202500730.

